import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/main-layout/header";
import FooterComponent from "@/components/main-layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={
          inter.className + " h-full flex flex-col container mx-auto px-4"
        }
      >
        <HeaderComponent />
        <div className="flex-1">{children}</div>
        <FooterComponent />
      </body>
    </html>
  );
}
